---
namespace: kravietz
name: yggdrasil
version: 0.1.0
readme: README.md
authors:
- Pawel Krawczyk
license:
- MIT
tags:
- networking
- security
- privacy
repository: "https://bitbucket.org/kravietz/ansible-yggdrasil/src/master/"
issues: "https://bitbucket.org/kravietz/ansible-yggdrasil/issues"
homepage: "https://bitbucket.org/kravietz/ansible-yggdrasil/"
documentation: "https://bitbucket.org/kravietz/ansible-yggdrasil/src/master/README.md"