---
- name: Prepare Debian/Ubuntu repositories
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  block:
    - name: Install gpg as required by apt_key
      ansible.builtin.apt:
        update_cache: true
        name: gnupg

    - name: Add Yggdrasil apt key
      ansible.builtin.apt_key:
        url: https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt

    - name: Add Yggdrasil apt repo
      ansible.builtin.apt_repository:
        repo: deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil

- name: Ensure python installed as required by Ansible
  ansible.builtin.package:
    name: python
  when: ansible_distribution == "Archlinux"

- name: Yggdrasil COPR repo
  community.general.copr:
    name: neilalexander/yggdrasil-go
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Yggdrasil package is installed
  ansible.builtin.package:
    name: yggdrasil

- name: Apparmor package is installed
  ansible.builtin.package:
    name: apparmor

- name: Update gai.conf label
  ansible.builtin.lineinfile:
    dest: /etc/gai.conf
    line: label 200::/7      15
    regexp: ^label\s+0?200::/7

- name: Update gai.conf precedence
  ansible.builtin.lineinfile:
    dest: /etc/gai.conf
    line: precedence 200::/7        90
    regexp: ^precedence\s+0?200::/7

- name: AppArmor policy for Yggdrasil
  ansible.builtin.copy:
    src: files/apparmor.conf
    dest: /etc/apparmor.d/usr.bin.yggdrasil
    validate: apparmor_parser -d %s
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload apparmor yggdrasil
  when: yggdrasil_apparmor

- name: Verify if keys are defined
  ansible.builtin.assert:
    that:
      - yggdrasil_config.PrivateKey is defined
      - yggdrasil_config.PublicKey is defined
    fail_msg: "When `yggdrasil_config` is defined, it must contain `PrivateKey` and `PublicKey`"
  when: yggdrasil_config is defined

- name: Disable handler for Molecule testing
  ansible.builtin.set_fact:
    handler_enabled: true
  tags: molecule-notest

- name: Yggdrasil configuration file
  ansible.builtin.template:
    src: templates/yggdrasil.conf.j2
    dest: /etc/yggdrasil.conf
    owner: root
    group: yggdrasil
    mode: 0640
    validate: yggdrasil -normaliseconf -useconf < %s
  when: yggdrasil_config is defined
  notify:
    - Restart yggdrasil

- name: Yggdrasil service
  ansible.builtin.service:
    name: yggdrasil
    state: "{{ yggdrasil_service_state }}"
    enabled: "{{ yggdrasil_service_enabled }}"
  tags: molecule-notest
