---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # the official ArchLinux image has no Python
    image: jahrik/docker-archlinux-ansible
provisioner:
  name: ansible
verifier:
  name: ansible
