---
- name: Restart yggdrasil
  ansible.builtin.service:
    name: yggdrasil
    state: restarted

- name: Reload apparmor yggdrasil
  ansible.builtin.command: apparmor_parser -r -W /etc/apparmor.d/usr.bin.yggdrasil

